/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as HomeRouteRouteImport } from './routes/_home/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as HomeCustomRouteImport } from './routes/_home/custom'
import { Route as HomeCartRouteImport } from './routes/_home/cart'
import { Route as HomeAboutRouteImport } from './routes/_home/about'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminCustomOrdersIndexRouteImport } from './routes/admin/custom-orders/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminProductsNewProductRouteImport } from './routes/admin/products/new-product'
import { Route as AdminOrdersNewOrderRouteImport } from './routes/admin/orders/new-order'
import { Route as AdminProductsIdUpdateProductRouteImport } from './routes/admin/products/$id/update-product'
import { Route as AdminOrdersIdUpdateOrderRouteImport } from './routes/admin/orders/$id/update-order'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeCustomRoute = HomeCustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeCartRoute = HomeCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeAboutRoute = HomeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HomeRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomOrdersIndexRoute = AdminCustomOrdersIndexRouteImport.update({
  id: '/custom-orders/',
  path: '/custom-orders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsNewProductRoute = AdminProductsNewProductRouteImport.update({
  id: '/products/new-product',
  path: '/products/new-product',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersNewOrderRoute = AdminOrdersNewOrderRouteImport.update({
  id: '/orders/new-order',
  path: '/orders/new-order',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIdUpdateProductRoute =
  AdminProductsIdUpdateProductRouteImport.update({
    id: '/products/$id/update-product',
    path: '/products/$id/update-product',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminOrdersIdUpdateOrderRoute =
  AdminOrdersIdUpdateOrderRouteImport.update({
    id: '/orders/$id/update-order',
    path: '/orders/$id/update-order',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/about': typeof HomeAboutRoute
  '/cart': typeof HomeCartRoute
  '/custom': typeof HomeCustomRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/orders/new-order': typeof AdminOrdersNewOrderRoute
  '/admin/products/new-product': typeof AdminProductsNewProductRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/custom-orders/': typeof AdminCustomOrdersIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/orders/$id/update-order': typeof AdminOrdersIdUpdateOrderRoute
  '/admin/products/$id/update-product': typeof AdminProductsIdUpdateProductRoute
}
export interface FileRoutesByTo {
  '/': typeof HomeIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/about': typeof HomeAboutRoute
  '/cart': typeof HomeCartRoute
  '/custom': typeof HomeCustomRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin/orders/new-order': typeof AdminOrdersNewOrderRoute
  '/admin/products/new-product': typeof AdminProductsNewProductRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/custom-orders': typeof AdminCustomOrdersIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/orders/$id/update-order': typeof AdminOrdersIdUpdateOrderRoute
  '/admin/products/$id/update-product': typeof AdminProductsIdUpdateProductRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_home': typeof HomeRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_home/about': typeof HomeAboutRoute
  '/_home/cart': typeof HomeCartRoute
  '/_home/custom': typeof HomeCustomRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/_home/': typeof HomeIndexRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/orders/new-order': typeof AdminOrdersNewOrderRoute
  '/admin/products/new-product': typeof AdminProductsNewProductRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/custom-orders/': typeof AdminCustomOrdersIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/orders/$id/update-order': typeof AdminOrdersIdUpdateOrderRoute
  '/admin/products/$id/update-product': typeof AdminProductsIdUpdateProductRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/about'
    | '/cart'
    | '/custom'
    | '/products/$slug'
    | '/account/'
    | '/admin/'
    | '/products/'
    | '/admin/orders/new-order'
    | '/admin/products/new-product'
    | '/api/auth/$'
    | '/admin/custom-orders/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/orders/$id/update-order'
    | '/admin/products/$id/update-product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/about'
    | '/cart'
    | '/custom'
    | '/products/$slug'
    | '/account'
    | '/admin'
    | '/products'
    | '/admin/orders/new-order'
    | '/admin/products/new-product'
    | '/api/auth/$'
    | '/admin/custom-orders'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/orders/$id/update-order'
    | '/admin/products/$id/update-product'
  id:
    | '__root__'
    | '/_auth'
    | '/_home'
    | '/admin'
    | '/_auth/login'
    | '/_auth/register'
    | '/_home/about'
    | '/_home/cart'
    | '/_home/custom'
    | '/products/$slug'
    | '/_home/'
    | '/account/'
    | '/admin/'
    | '/products/'
    | '/admin/orders/new-order'
    | '/admin/products/new-product'
    | '/api/auth/$'
    | '/admin/custom-orders/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/orders/$id/update-order'
    | '/admin/products/$id/update-product'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ProductsSlugRoute: typeof ProductsSlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/custom': {
      id: '/_home/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof HomeCustomRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/cart': {
      id: '/_home/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof HomeCartRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/about': {
      id: '/_home/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof HomeAboutRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/custom-orders/': {
      id: '/admin/custom-orders/'
      path: '/custom-orders'
      fullPath: '/admin/custom-orders/'
      preLoaderRoute: typeof AdminCustomOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new-product': {
      id: '/admin/products/new-product'
      path: '/products/new-product'
      fullPath: '/admin/products/new-product'
      preLoaderRoute: typeof AdminProductsNewProductRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/new-order': {
      id: '/admin/orders/new-order'
      path: '/orders/new-order'
      fullPath: '/admin/orders/new-order'
      preLoaderRoute: typeof AdminOrdersNewOrderRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/$id/update-product': {
      id: '/admin/products/$id/update-product'
      path: '/products/$id/update-product'
      fullPath: '/admin/products/$id/update-product'
      preLoaderRoute: typeof AdminProductsIdUpdateProductRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/$id/update-order': {
      id: '/admin/orders/$id/update-order'
      path: '/orders/$id/update-order'
      fullPath: '/admin/orders/$id/update-order'
      preLoaderRoute: typeof AdminOrdersIdUpdateOrderRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface HomeRouteRouteChildren {
  HomeAboutRoute: typeof HomeAboutRoute
  HomeCartRoute: typeof HomeCartRoute
  HomeCustomRoute: typeof HomeCustomRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeAboutRoute: HomeAboutRoute,
  HomeCartRoute: HomeCartRoute,
  HomeCustomRoute: HomeCustomRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersNewOrderRoute: typeof AdminOrdersNewOrderRoute
  AdminProductsNewProductRoute: typeof AdminProductsNewProductRoute
  AdminCustomOrdersIndexRoute: typeof AdminCustomOrdersIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminOrdersIdUpdateOrderRoute: typeof AdminOrdersIdUpdateOrderRoute
  AdminProductsIdUpdateProductRoute: typeof AdminProductsIdUpdateProductRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersNewOrderRoute: AdminOrdersNewOrderRoute,
  AdminProductsNewProductRoute: AdminProductsNewProductRoute,
  AdminCustomOrdersIndexRoute: AdminCustomOrdersIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminOrdersIdUpdateOrderRoute: AdminOrdersIdUpdateOrderRoute,
  AdminProductsIdUpdateProductRoute: AdminProductsIdUpdateProductRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ProductsSlugRoute: ProductsSlugRoute,
  AccountIndexRoute: AccountIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
